import { Campaign } from "../types/campaign-table";

export const CampaignData: Campaign[] = [
    {
      CampaignId: "CMP001",
      CampaignName: "Summer Promo",
      DialMethod: "Predictive",
      AutoDialLevel: 3,
      Status:{currentStatus: "Active"},
      Lists: ["List_A", "List_B"],
      LeadOrder: "Random",
      UserGroup: "SalesTeam",
      HopperCount: 25,
      CallerID: "+1-800-555-1001",
    },
    {
      CampaignId: "CMP002",
      CampaignName: "Winter Deals",
      DialMethod: "Manual",
      AutoDialLevel: 1,
      Status:{currentStatus: "active"},
      Lists: ["List_C"],
      LeadOrder: "ASC",
      UserGroup: "SupportTeam",
      HopperCount: 12,
      CallerID: "+1-800-555-1002",
    },
    {
      CampaignId: "CMP003",
      CampaignName: "Flash Sale",
      DialMethod: "Preview",
      AutoDialLevel: 2,
      Status:{currentStatus: "Inactive"},
      Lists: ["List_D", "List_E"],
      LeadOrder: "DESC",
      UserGroup: "Marketing",
      HopperCount: 8,
      CallerID: "+1-800-555-1003",
    },
    {
      CampaignId: "CMP004",
      CampaignName: "New Year Blast",
      DialMethod: "Predictive",
      AutoDialLevel: 4,
      Status:{currentStatus: "Active"},
      Lists: ["List_F"],
      LeadOrder: "Random",
      UserGroup: "SalesTeam",
      HopperCount: 20,
      CallerID: "+1-800-555-1004",
    },
    {
      CampaignId: "CMP005",
      CampaignName: "Spring Offers",
      DialMethod: "Manual",
      AutoDialLevel: 1,
      Status:{currentStatus: "Inactive"},
      Lists: ["List_G", "List_H"],
      LeadOrder: "ASC",
      UserGroup: "SupportTeam",
      HopperCount: 15,
      CallerID: "+1-800-555-1005",
    },
    {
      CampaignId: "CMP006",
      CampaignName: "Holiday Special",
      DialMethod: "Preview",
      AutoDialLevel: 2,
      Status:{currentStatus: "Active"},
      Lists: ["List_I"],
      LeadOrder: "DESC",
      UserGroup: "Marketing",
      HopperCount: 18,
      CallerID: "+1-800-555-1006",
    },
    {
      CampaignId: "CMP007",
      CampaignName: "Black Friday",
      DialMethod: "Predictive",
      AutoDialLevel: 5,
      Status:{currentStatus: "Inactive"},
      Lists: ["List_J", "List_K"],
      LeadOrder: "Random",
      UserGroup: "SalesTeam",
      HopperCount: 30,
      CallerID: "+1-800-555-1007",
    },
    {
      CampaignId: "CMP008",
      CampaignName: "Cyber Monday",
      DialMethod: "Manual",
      AutoDialLevel: 2,
      Status:{currentStatus: "Inactive"},
      Lists: ["List_L"],
      LeadOrder: "ASC",
      UserGroup: "SupportTeam",
      HopperCount: 10,
      CallerID: "+1-800-555-1008",
    },
    {
      CampaignId: "CMP009",
      CampaignName: "Weekend Bonanza",
      DialMethod: "Preview",
      AutoDialLevel: 3,
      Status:{currentStatus: "Active"},
      Lists: ["List_M", "List_N"],
      LeadOrder: "DESC",
      UserGroup: "Marketing",
      HopperCount: 22,
      CallerID: "+1-800-555-1009",
    },
    {
      CampaignId: "CMP010",
      CampaignName: "Festival Rush",
      DialMethod: "Predictive",
      AutoDialLevel: 4,
      Status:{currentStatus: "Active"},
      Lists: ["List_O"],
      LeadOrder: "Random",
      UserGroup: "SalesTeam",
      HopperCount: 28,
      CallerID: "+1-800-555-1010",
    },
  ];